### ISSUE TITLE
路由路由前置守卫似乎无效

### ISSUE THREAD

**Issue by hsk-story** [viarotel-org/vite-uniapp-template#1]
手动访问/pages/home/tab-0/index地址, 有触发next方法, 但是页面没有跳转

**Comment by viarotel** [comment]
这个问题是已知的, 依赖的 uni-native-router 本身有这个问题 我会在晚点时间尝试解决

**Comment by aron0524** [comment]
配置 404 页面
如果在pages.json里面找不到对应的路由会尝试找到pages.json里面的name为notfound的页面不限大小写

{
  "path": "pages/not-found/index",
  "name": "notfound",
  "style": {
    "navigationBarTitleText": "NotFound"
  }
}

**Comment by viarotel** [comment]
最近没有空 等下个版本大修复吧 或者自己尝试解决以后提PR
