### ISSUE TITLE
编译到小程序报错

### ISSUE THREAD

**Issue by zarvin** [viarotel-org/vite-uniapp-template#23]
`
[plugin:vite:vue] v-bind="" is not supported.
at pages/webview/index.vue:2:28
`
启动时，报上面的错误

**Comment by viarotel** [comment]
小程序端编译v-bind没有通过，你先手动改一下语法吧，回头我更新一下

**Comment by viarotel** [comment]
小程序中自定义组件支持 v-bind 但是内置的组件不支持 v-bind

**Comment by viarotel** [comment]
v2.5.3 已解决该问题
