### ISSUE TITLE
App端返回会进入404页面，进入之后无法再返回

### ISSUE THREAD

**Issue by HeHong1** [viarotel-org/vite-uniapp-template#25]
如题，在`main.ts`注释调`use(router)`即可正常，`uni-router`存在问题

**Comment by viarotel** [comment]
因为依赖的 [uniapp-router-next](https://www.npmjs.com/package/uniapp-router-next) 暂未对APP端进行测试和支持 我这边抽时间了测试一下看好解决不 谢谢反馈

**Comment by viarotel** [comment]
[v2.5.5](https://github.com/viarotel-org/vite-uniapp-template/releases/tag/v2.5.5) 版本已解决该问题
