### ISSUE TITLE
mac上pnpm install 依赖安装不全

### ISSUE THREAD

**Issue by LeftProgrammer** [viarotel-org/vite-uniapp-template#33]
![image](https://github.com/viarotel-org/vite-uniapp-template/assets/30935024/c5013e8a-caf8-4b7d-8d11-3919971be51c)

**Comment by LeftProgrammer** [comment]
node版本18 、 20 都试过，pnpm版本8以上

**Comment by LeftProgrammer** [comment]
mac 使用yarn安装依赖，启动正常

**Comment by viarotel** [comment]
很久没有在macos上测试过了，回头我试试，找找原因

**Comment by DM1-1** [comment]
提供数据：
MACOS Ventura 13.4
pnpm v8.13.1
node v21.4.0
能够正常下载依赖
<img width="223" alt="image" src="https://github.com/viarotel-org/vite-uniapp-template/assets/88864535/77e22513-f07d-4b5c-9898-7df6af4c4abe">
