### ISSUE TITLE
你这框架问题太多

### ISSUE THREAD

**Issue by lihanqiang** [viarotel-org/vite-uniapp-template#44]
1 为何不锁定node(npm)版本;
2 为何不锁定依赖版本;
3 你多平台测试没有?

**Comment by viarotel** [comment]
你好，如你所说，我确实挺久没有维护该模板，因为最近没有做Uniapp相关项目，所以我没有动力去更新它，并且我确实没有更多的精力投入到这上面，如果确实遇到问题请尝试自行解决。感谢你的反馈。
